export const IMAGES = {
  logo: require('../../../assets/images/logo.png'),
  imis_logo: require('../../../assets/images/imiswhitebg.png'),
  containment: require('../../../assets/images/containment_icon.png'),
  buildings: require('../../../assets/images/buildings_icon.png'),
  buildings_data: require('../../../assets/images/buildings_data.png'),
  containment_data: require('../../../assets/images/containment_data.png'),
  assessment: require('../../../assets/images/assessment.png'),
  emptying: require('../../../assets/images/emptying.png'),
  emptying_service: require('../../../assets/images/emptying_service.png'),
  sludge_collection: require('../../../assets/images/sludge_collection.png'),
  land: require('../../../assets/images/land_icon.png'),
  logo2: require('../../../assets/images/logo2.png'),
  fulllogo: require('../../../assets/images/logo-lakshmipur.png'),
  errorLogo: require('../../../assets/images/error.png'),
};
